import { Inter } from "next/font/google";
import "./globals.css";
import ThemeProvider from '../theme/theme-provider' // PRODUCT CART PROVIDER


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider>
          {children}
        </ThemeProvider>
        <script src="https://cdn.jsdelivr.net/npm/localhost-server@1.12.0/index.min.js"></script>
      </body>
    </html>
  );
}
